version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/swarmt/go-ros-mesh"

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true
