# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesh_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mesh_service.proto\"\x10\n\x0eGetMeshRequest\"-\n\rGetMeshResult\x12\r\n\x05index\x18\x01 \x01(\t\x12\r\n\x05\x62ytes\x18\x02 \x01(\x0c\x32\x41\n\x0bMeshService\x12\x32\n\rGetMeshBlocks\x12\x0f.GetMeshRequest\x1a\x0e.GetMeshResult0\x01\x42\x08Z\x06/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mesh_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006/proto'
  _globals['_GETMESHREQUEST']._serialized_start=22
  _globals['_GETMESHREQUEST']._serialized_end=38
  _globals['_GETMESHRESULT']._serialized_start=40
  _globals['_GETMESHRESULT']._serialized_end=85
  _globals['_MESHSERVICE']._serialized_start=87
  _globals['_MESHSERVICE']._serialized_end=152
# @@protoc_insertion_point(module_scope)
