# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mesh_service_pb2 as mesh__service__pb2


class MeshServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeshBlocks = channel.unary_stream(
                '/MeshService/GetMeshBlocks',
                request_serializer=mesh__service__pb2.GetMeshRequest.SerializeToString,
                response_deserializer=mesh__service__pb2.GetMeshResult.FromString,
                )


class MeshServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMeshBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeshBlocks': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMeshBlocks,
                    request_deserializer=mesh__service__pb2.GetMeshRequest.FromString,
                    response_serializer=mesh__service__pb2.GetMeshResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeshService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMeshBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/MeshService/GetMeshBlocks',
            mesh__service__pb2.GetMeshRequest.SerializeToString,
            mesh__service__pb2.GetMeshResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
