// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/mesh_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeshRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMeshRequest) Reset() {
	*x = GetMeshRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mesh_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeshRequest) ProtoMessage() {}

func (x *GetMeshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeshRequest.ProtoReflect.Descriptor instead.
func (*GetMeshRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_service_proto_rawDescGZIP(), []int{0}
}

type GetMeshResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Bytes []byte `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *GetMeshResult) Reset() {
	*x = GetMeshResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mesh_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMeshResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeshResult) ProtoMessage() {}

func (x *GetMeshResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeshResult.ProtoReflect.Descriptor instead.
func (*GetMeshResult) Descriptor() ([]byte, []int) {
	return file_proto_mesh_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeshResult) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *GetMeshResult) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_proto_mesh_service_proto protoreflect.FileDescriptor

var file_proto_mesh_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x32, 0x41, 0x0a, 0x0b, 0x4d, 0x65, 0x73,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x73, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mesh_service_proto_rawDescOnce sync.Once
	file_proto_mesh_service_proto_rawDescData = file_proto_mesh_service_proto_rawDesc
)

func file_proto_mesh_service_proto_rawDescGZIP() []byte {
	file_proto_mesh_service_proto_rawDescOnce.Do(func() {
		file_proto_mesh_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mesh_service_proto_rawDescData)
	})
	return file_proto_mesh_service_proto_rawDescData
}

var file_proto_mesh_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mesh_service_proto_goTypes = []interface{}{
	(*GetMeshRequest)(nil), // 0: GetMeshRequest
	(*GetMeshResult)(nil),  // 1: GetMeshResult
}
var file_proto_mesh_service_proto_depIdxs = []int32{
	0, // 0: MeshService.GetMeshBlocks:input_type -> GetMeshRequest
	1, // 1: MeshService.GetMeshBlocks:output_type -> GetMeshResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mesh_service_proto_init() }
func file_proto_mesh_service_proto_init() {
	if File_proto_mesh_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mesh_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeshRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mesh_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMeshResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mesh_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mesh_service_proto_goTypes,
		DependencyIndexes: file_proto_mesh_service_proto_depIdxs,
		MessageInfos:      file_proto_mesh_service_proto_msgTypes,
	}.Build()
	File_proto_mesh_service_proto = out.File
	file_proto_mesh_service_proto_rawDesc = nil
	file_proto_mesh_service_proto_goTypes = nil
	file_proto_mesh_service_proto_depIdxs = nil
}
